### ISSUE TITLE
java.lang.IllegalArgumentException: 'URI is not hierarchical' on startup with logging integration

### ISSUE THREAD

**Issue by mikolajgrajek** [stackify/stackify-api-java#17]
Hello,

when logging integration is enabled (logback) ApiConfigurations tries to load unsuccessfully  'stackify-api.properties' from class-path.

```
java.lang.IllegalArgumentException: URI is not hierarchical
         at java.io.File.<init>(File.java:418)
        at com.stackify.api.common.ApiConfigurations.fromProperties(ApiConfigurations.java:90)
        at com.stackify.api.common.ApiConfigurations.fromPropertiesWithOverrides(ApiConfigurations.java:59)
        at com.stackify.log.logback.StackifyLogAppender.start(StackifyLogAppender.java:176)
```

Problem lies with resource access when 'stackify-api.properties' is within jar package:

```java
URL confFileUrl = ApiConfigurations.class.getResource("/stackify-api.properties");			
if (confFileUrl != null) {
 File confFile = new File(confFileUrl.toURI());
...
```
(maybe `getResourceAsStream(...)` could be used here instead? )

It's not critical (everything works anyway), however few big stack traces at the start look scary :)

Sincerely

**Comment by darinhoward** [comment]
I've updated how we load in the stackify-api.properties. Thank you for opening this ticket.
